# Generated by Django 3.2.3 on 2025-02-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ингредиент')),
                ('measurement_unit', models.CharField(max_length=5, verbose_name='Единица измерения')),
            ],
        ),
    ]
