# Generated by Django 3.2.3 on 2025-01-28 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='favourited_by_users',
            new_name='users_who_favourited_this',
        ),
        migrations.AddField(
            model_name='recipe',
            name='users_who_put_this_in_shopping_list',
            field=models.ManyToManyField(related_name='_recipes_recipe_users_who_put_this_in_shopping_list_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
