# Generated by Django 3.2.3 on 2025-01-29 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20250128_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='users_who_favourited_this',
            field=models.ManyToManyField(blank=True, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='users_who_put_this_in_shopping_list',
            field=models.ManyToManyField(blank=True, related_name='_recipes_recipe_users_who_put_this_in_shopping_list_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
