# Generated by Django 3.2.3 on 2025-02-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20250129_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='minutes_to_cook',
            new_name='cooking_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='text',
            field=models.TextField(default='borpa', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
