# Generated by Django 3.2.3 on 2025-02-15 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_auto_20250215_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ManyToManyField(related_name='recipes_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
