# Generated by Django 3.2.3 on 2025-02-19 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('recipes', '0007_auto_20250215_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tag_recipes', to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='users_who_favourited_this',
            field=models.ManyToManyField(blank=True, related_name='user_favorites_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='users_who_put_this_in_shopping_list',
            field=models.ManyToManyField(blank=True, related_name='user_shopping_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
