# Generated by Django 5.1.6 on 2025-03-02 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipe_users_who_favorited_this_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время готовки не может быть меньше 1'), django.core.validators.MaxValueValidator(32000, 'Время готовки не может быть больше 32000')], verbose_name='Время приготовления в минутах'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Количество ингредиента не может быть меньше 1'), django.core.validators.MaxValueValidator(32000, 'Количество ингредиента не может быть больше 32000')], verbose_name='Количество'),
        ),
    ]
