# Generated by Django 3.2.3 on 2025-02-19 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_auto_20250219_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='users_who_favourited_this',
            field=models.ManyToManyField(blank=True, related_name='favorites_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='users_who_put_this_in_shopping_list',
            field=models.ManyToManyField(blank=True, related_name='shopping_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
