# Generated by Django 3.2.3 on 2025-02-19 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0009_auto_20250219_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='users_who_put_this_in_shopping_list',
        ),
        migrations.AddField(
            model_name='recipe',
            name='users_who_put_this_in_shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='shopping_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
