# Generated by Django 3.2.3 on 2025-02-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20250219_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
